export function registerCiaDarkTheme(monaco) {
  monaco.editor.defineTheme('cia-dark', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment',           foreground: '484f58', fontStyle: 'italic' },
      { token: 'keyword',           foreground: 'ff7b72' },
      { token: 'string',            foreground: 'a5d6ff' },
      { token: 'number',            foreground: 'f2cc60' },
      { token: 'type',              foreground: 'ffa657' },
      { token: 'function',          foreground: 'd2a8ff' },
      { token: 'variable',          foreground: 'e6edf3' },
      { token: 'variable.parameter',foreground: 'ffa657' },
      { token: 'constant',          foreground: '79c0ff' },
      { token: 'operator',          foreground: 'ff7b72' },
      { token: 'delimiter',         foreground: '8b949e' },
      { token: 'tag',               foreground: '7ee787' },
      { token: 'attribute.name',    foreground: 'ffa657' },
      { token: 'attribute.value',   foreground: 'a5d6ff' },
    ],
    colors: {
      'editor.background':              '#0d1117',
      'editor.foreground':              '#e6edf3',
      'editor.lineHighlightBackground': '#161b2280',
      'editor.selectionBackground':     '#264f7840',
      'editor.inactiveSelectionBackground': '#264f7820',
      'editorLineNumber.foreground':    '#484f58',
      'editorLineNumber.activeForeground': '#8b949e',
      'editorCursor.foreground':        '#58a6ff',
      'editorWhitespace.foreground':    '#21282f',
      'editorIndentGuide.background':   '#21282f',
      'editorIndentGuide.activeBackground': '#30363d',
      'editor.findMatchBackground':     '#f2cc6040',
      'editor.findMatchHighlightBackground': '#f2cc6020',
      'editorBracketMatch.background':  '#58a6ff20',
      'editorBracketMatch.border':      '#58a6ff',
      'scrollbarSlider.background':     '#21283a80',
      'scrollbarSlider.hoverBackground':'#2a334880',
      'minimap.background':             '#0d1117',
      'editorGutter.background':        '#0d1117',
      'editorSuggestWidget.background': '#161b22',
      'editorSuggestWidget.border':     '#30363d',
      'editorSuggestWidget.selectedBackground': '#2a3348',
    },
  });
}
